Repository CUCyber/cucyber.github.io, pull requests merged in 2020-04, with the labels that each got.

#43 Update page footer to use updated themefisher link
  _layouts/default.html
Labels: bug

#38 Update linkedin link to use CUCyber group
  _layouts/default.html
Labels: bug

#39 Update about.html links to use https
  about.html
Labels: bug

#45 Add Open Graph tags to show cool stuff when posted on social media
  _config.yml
  _layouts/default.html
Labels: enhancement

#44 Add fullcalendar version of events page
  _layouts/default.html
  css/main.css
  css/responsive.css
  events.html
Labels: bug

#46 Replace cucyber pngs with our svg
  _layouts/default.html
  about.html
  css/main.css
  css/responsive.css
  images/logo.png
  images/logo.svg
  images/shield-small.png
  images/shield.svg
Labels: enhancement

#49 Add Additional Social Media Icons/Links
  _layouts/default.html
Labels: enhancement

#51 Move Scripts and Stylesheets to CDN if Possible
  _layouts/default.html
  css/animate.css
  css/bootstrap.min.css
  css/ionicons.min.css
  css/jquery.fancybox.css
  css/owl.carousel.css
  css/owl.theme.css
  css/slider.css
  fonts/ionicons.eot
  fonts/ionicons.svg
  fonts/ionicons.ttf
  fonts/ionicons.woff
  js/bootstrap.min.js
  js/jquery.fancybox.js
  js/jquery.min.js
  js/owl.carousel.min.js
  js/vendor/html5shiv-printshiv.min.js
  js/wow.min.js
Labels: bug, enhancement

#50 Remove "Home" Link in Navigation Bar
  _layouts/default.html
Labels: bug

#52 Implement securitytxt Standard
  _layouts/default.html
  css/main.css
  css/responsive.css
  cyber.asc
  security.html
  security.txt
Labels: enhancement

#47 Add humans.txt file with officers, contributors, and software components
  _layouts/default.html
  humans.txt
Labels: enhancement

#54 Update Contacts Page with 2020 Officers
  contact.html
  css/main.css
  images/team/adam.jpg
  images/team/cameron.jpg
  images/team/kaitlyn.jpg
  images/team/matthew_b.jpg
  images/team/matthew_e.jpg
  images/team/matthew_r.jpg
  images/team/max.jpg
Labels: bug

#55 Change "cybersecurity" to "cyber security" (with a space)
  about.html
Labels: bug

#56 Adjust Security Acknowledgements Link
  _layouts/default.html
Labels: bug

#57 Add Pre-2016 Achievements
  about.html
Labels: enhancement
